package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import url "net/url"

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// Request provides a mock function with given fields: ctx, uri
func (_m *Requester) Request(ctx context.Context, uri *url.URL) ([]byte, error) {
	ret := _m.Called(ctx, uri)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, *url.URL) []byte); ok {
		r0 = rf(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *url.URL) error); ok {
		r1 = rf(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
